#!/usr/bin/env python

Import("env")
Import("env_modules")

env_storereviewcontroller = env_modules.Clone()

# (OSX) Enable module support
env_storereviewcontroller.Append(CCFLAGS=["-fmodules", "-fcxx-modules"])

# (OSX) Build as separate static library
modules_sources = []
env_storereviewcontroller.add_source_files(modules_sources, "*.mm")
env_storereviewcontroller.add_source_files(modules_sources, "*.cpp")