#!/usr/bin/env python

Import("env")
Import("env_modules")

env_spotlight = env_modules.Clone()

if env["platform"] == "osx":
    env_spotlight.add_source_files(env.modules_sources, "*.mm")
    env_spotlight.add_source_files(env.modules_sources, "*.cpp")