#!/usr/bin/env python

Import("env")
Import("env_modules")

env_inappstore = env_modules.Clone()

if env["platform"] == "osx":
    env_inappstore.add_source_files(env.modules_sources, "*.mm")
    env_inappstore.add_source_files(env.modules_sources, "*.cpp")